# Generated by Django 5.0.3 on 2024-04-14 15:14

import django.db.models.deletion
import root.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag_line', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('ward_no', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=root.utils.UploadToPathAndRename('logos'))),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
