# Generated by Django 5.0.3 on 2024-04-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_department_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
    ]
