# Generated by Django 5.0.3 on 2024-04-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_designation_allow_multiple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='allow_multiple',
            new_name='allow_multiple_employees',
        ),
    ]
