# Generated by Django 5.2.5 on 2025-08-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_organization_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='organization',
        ),
    ]
