# Generated by Django 5.2.5 on 2025-08-19 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_remove_designation_organization_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('allow_multiple_employees', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('department_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_templates', to='organization.departmenttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='departmenttemplate',
            name='organization_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_templates', to='organization.organizationtemplate'),
        ),
    ]
