# Generated by Django 5.2.5 on 2025-09-06 07:14

import django.db.models.deletion
import root.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=root.utils.UploadToPathAndRename('profile_pictures'))),
                ('is_available', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.designation')),
            ],
        ),
    ]
