# Generated by Django 5.0.3 on 2024-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
