# Generated by Django 5.0.3 on 2024-04-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='description',
            new_name='remarks',
        ),
    ]
