# Generated by Django 5.0.3 on 2024-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_rename_remarks_employee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
