# Generated by Django 5.0.3 on 2024-04-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture_url',
        ),
    ]
