# Generated by Django 5.0.3 on 2024-07-09 10:16

import root.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.jpg', null=True, upload_to=root.utils.UploadToPathAndRename('profile_pictures')),
        ),
    ]
