# Generated by Django 5.0.3 on 2024-07-09 10:30

import root.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=root.utils.UploadToPathAndRename('profile_pictures')),
        ),
    ]
