# Generated by Django 5.2.5 on 2025-08-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
    ]
