services:
  web:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - django_db:/app/data
      - django_media:/app/public/media
    environment:
      - DEBUG=1
    env_file:
      - .env
    command: uv run python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      db-init:
        condition: service_completed_successfully

  db-init:
    build:
      context: .
      target: development
    volumes:
      - django_db:/app/data
      - django_media:/app/public/media
    env_file:
      - .env
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python  manage.py collectstatic --noinput"

volumes:
  django_db:
    driver: local
  django_media:
    driver: local
