# Generated by Django 5.2.5 on 2025-08-23 08:41

import django.db.models.deletion
import root.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0016_alter_employee_description'),
        ('organization', '0014_departmenttemplate_organizationtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organizations', models.ManyToManyField(blank=True, help_text='Organizations that are allowed to offer this service.         Leave blank if available to all.', related_name='available_services', to='organization.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_documents', models.TextField(help_text='List of required documents, one per line.')),
                ('process_flow', models.TextField(help_text='Describe the process flow for the service, one step per line.')),
                ('fees', models.CharField(default='Free', help_text="e.g., 'Rs. 500' or 'Free'", max_length=100)),
                ('timeline', models.CharField(help_text="e.g., '3 working days'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this service currently offered by the organization?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='organization.organization')),
                ('responsible_employees', models.ManyToManyField(blank=True, help_text='Select employees responsible for this service.', to='employee.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='service.service')),
            ],
            options={
                'verbose_name': "Organization's Service Detail",
                'verbose_name_plural': "Organization's Service Details",
                'unique_together': {('organization', 'service')},
            },
        ),
        migrations.CreateModel(
            name='SampleDocments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Application Form'", max_length=255)),
                ('file', models.FileField(upload_to=root.utils.UploadToPathAndRename('sample_documents'))),
                ('is_active', models.BooleanField(default=True, help_text='Is this sample document still releavent?')),
                ('service_detail', models.ForeignKey(help_text='The service this document is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='sample_documents', to='service.servicedetail')),
            ],
            options={
                'verbose_name': 'Sample Document',
                'verbose_name_plural': 'Sample Documents',
            },
        ),
    ]
