name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Install sshpass
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: Adding ssh-key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server & restart
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -T ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          cd ${{ secrets.PATH }}
          ${{ secrets.DEPLOY_COMMAND }}
          ${{secrets.ACTIVATE_VENV_COMMAND }}
          ${{ secrets.INSTALL_REQ_COMMAND }}
          ${{ secrets.MIGRATE_COMMAND }}
          ${{ secrets.COLLECT_STATIC_COMMAND }}
          ${{ secrets.RESTART_COMMAND }}
