name: Docker test and publish image

on:
  push:
    branches: [ main ]

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Initial config for docker-compose
      run: |
        ln -s docker/docker-compose.test.yml docker-compose.yml

    - name: Run test
      run: |
        docker compose up --exit-code-from web

  publish-image:
    runs-on: ubuntu-latest
    needs: test-image
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Initial config for docker-compose
      run: |
        ln -s docker/docker-compose.prod.yml docker-compose.yml

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/digital-citizen-charter-api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/digital-citizen-charter-api:${{ github.sha }}
